import type { CompanyProfile } from '../core/schema/profile.js';

const C = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  cyan: '\x1b[36m',
  yellow: '\x1b[33m',
  green: '\x1b[32m',
};

function citeMarker(citations: number[]): string {
  if (!citations.length) return '';
  return ` [${citations.map((c) => c + 1).join(',')}]`;
}

/** Render a dossier as a readable terminal report. `color` toggles ANSI codes. */
export function renderDossier(profile: CompanyProfile, opts: { color?: boolean } = {}): string {
  const color = opts.color ?? true;
  const c = (code: string, s: string) => (color ? code + s + C.reset : s);
  const lines: string[] = [];

  const header = profile.domain ? `${profile.name}  (${profile.domain})` : profile.name;
  lines.push(c(C.bold + C.cyan, header));
  if (profile.tagline) lines.push(c(C.dim, profile.tagline));
  lines.push('');
  if (profile.summary) {
    lines.push(profile.summary);
    lines.push('');
  }

  if (profile.facts.length) {
    lines.push(c(C.bold, 'Facts'));
    for (const f of profile.facts) {
      lines.push(`  • ${c(C.yellow, f.label)}: ${f.value}${c(C.dim, citeMarker(f.citations))}`);
    }
    lines.push('');
  }

  if (profile.funding.length) {
    lines.push(c(C.bold, 'Funding'));
    for (const r of profile.funding) {
      const bits = [r.stage, r.amount, r.date].filter(Boolean).join(' · ');
      const investors = r.investors?.length ? ` (${r.investors.join(', ')})` : '';
      lines.push(`  • ${bits}${investors}${c(C.dim, citeMarker(r.citations))}`);
    }
    lines.push('');
  }

  if (profile.competitors.length) {
    lines.push(c(C.bold, 'Competitors') + ': ' + profile.competitors.join(', '));
    lines.push('');
  }

  if (profile.swot) {
    const s = profile.swot;
    const part = (label: string, items: string[]) =>
      items.length ? `  ${c(C.yellow, label)}: ${items.join('; ')}` : '';
    const swot = [
      part('Strengths', s.strengths),
      part('Weaknesses', s.weaknesses),
      part('Opportunities', s.opportunities),
      part('Threats', s.threats),
    ].filter(Boolean);
    if (swot.length) {
      lines.push(c(C.bold, 'SWOT'));
      lines.push(...swot);
      lines.push('');
    }
  }

  lines.push(c(C.bold, 'Sources'));
  profile.sources.forEach((s, i) => {
    const date = s.fetchedAt.slice(0, 10);
    lines.push(`  ${c(C.green, `[${i + 1}]`)} ${s.title} — ${s.url} ${c(C.dim, `(${date})`)}`);
  });
  lines.push('');

  const model = profile.meta.model ? ` (${profile.meta.model})` : '';
  lines.push(
    c(
      C.dim,
      `Generated by ${profile.meta.generator}${model} · confidence: ${profile.meta.confidence} · ${profile.meta.generatedAt.slice(0, 10)}`,
    ),
  );
  if (profile.meta.notes) lines.push(c(C.dim, profile.meta.notes));

  return lines.join('\n');
}
