import type { CompanyProfile } from '../core/schema/profile.js';

const C = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  cyan: '\x1b[36m',
  yellow: '\x1b[33m',
  green: '\x1b[32m',
};

// Field values come from fetched web pages / LLM output. Strip ANSI/OSC escape sequences
// and other control characters so a hostile source can't inject terminal-control bytes
// (title spoofing, screen clears) into the rendered report.
// eslint-disable-next-line no-control-regex
const OSC = /\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)/g;
// eslint-disable-next-line no-control-regex
const CSI = /\x1b\[[0-9;?]*[ -/]*[@-~]/g;
// eslint-disable-next-line no-control-regex
const CTRL = /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g;
function clean(s: string): string {
  return s.replace(OSC, '').replace(CSI, '').replace(CTRL, '');
}

function citeMarker(citations: number[]): string {
  if (!citations.length) return '';
  return ` [${citations.map((c) => c + 1).join(',')}]`;
}

/** Render a dossier as a readable terminal report. `color` toggles ANSI codes. */
export function renderDossier(profile: CompanyProfile, opts: { color?: boolean } = {}): string {
  const color = opts.color ?? true;
  const c = (code: string, s: string) => (color ? code + s + C.reset : s);
  const lines: string[] = [];

  const name = clean(profile.name);
  const header = profile.domain ? `${name}  (${clean(profile.domain)})` : name;
  lines.push(c(C.bold + C.cyan, header));
  if (profile.tagline) lines.push(c(C.dim, clean(profile.tagline)));
  lines.push('');
  if (profile.summary) {
    lines.push(clean(profile.summary));
    lines.push('');
  }

  if (profile.facts.length) {
    lines.push(c(C.bold, 'Facts'));
    for (const f of profile.facts) {
      lines.push(`  • ${c(C.yellow, clean(f.label))}: ${clean(f.value)}${c(C.dim, citeMarker(f.citations))}`);
    }
    lines.push('');
  }

  // Skip rounds with no renderable content (all optional fields empty) — they'd be a bare bullet.
  const funding = profile.funding.filter((r) => r.stage || r.amount || r.date || r.investors?.length);
  if (funding.length) {
    lines.push(c(C.bold, 'Funding'));
    for (const r of funding) {
      const bits = [r.stage, r.amount, r.date].filter(Boolean).map((s) => clean(s as string)).join(' · ');
      const investors = r.investors?.length ? ` (${r.investors.map(clean).join(', ')})` : '';
      lines.push(`  • ${bits}${investors}${c(C.dim, citeMarker(r.citations))}`);
    }
    lines.push('');
  }

  if (profile.competitors.length) {
    lines.push(c(C.bold, 'Competitors') + ': ' + profile.competitors.map(clean).join(', '));
    lines.push('');
  }

  if (profile.swot) {
    const s = profile.swot;
    const part = (label: string, items: string[]) =>
      items.length ? `  ${c(C.yellow, label)}: ${items.map(clean).join('; ')}` : '';
    const swot = [
      part('Strengths', s.strengths),
      part('Weaknesses', s.weaknesses),
      part('Opportunities', s.opportunities),
      part('Threats', s.threats),
    ].filter(Boolean);
    if (swot.length) {
      lines.push(c(C.bold, 'SWOT'));
      lines.push(...swot);
      lines.push('');
    }
  }

  if (profile.sources.length) {
    lines.push(c(C.bold, 'Sources'));
    profile.sources.forEach((s, i) => {
      const date = s.fetchedAt.slice(0, 10);
      lines.push(`  ${c(C.green, `[${i + 1}]`)} ${clean(s.title)} — ${clean(s.url)} ${c(C.dim, `(${date})`)}`);
    });
    lines.push('');
  }

  const model = profile.meta.model ? ` (${clean(profile.meta.model)})` : '';
  lines.push(
    c(
      C.dim,
      `Generated by ${profile.meta.generator}${model} · confidence: ${profile.meta.confidence} · ${profile.meta.generatedAt.slice(0, 10)}`,
    ),
  );
  if (profile.meta.notes) lines.push(c(C.dim, clean(profile.meta.notes)));

  return lines.join('\n');
}
